window.MENU_EN = {
  categories: [
  {
      id: "specials",
      label: "Specials",
      items: [
        {code: "S01", name: "Winter Tomato", desc: "roasted tomato, katak (Bulgarian dairy spread), olives, walnuts, wild garlic pesto", eur: 7.11, bgn: 13.90, weight: "400 g"},
        {code: "S02", name: "Fermented Vegetables", desc: "traditional lacto-fermented mixed vegetables", eur: 5.22, bgn: 10.20, weight: "300 g"},
        {code: "S03", name: "Paprika u Pavlak", desc: "spicy Serbian-style spread with raw chili peppers and sour cream", eur: 5.06, bgn: 9.90, weight: "200 g"},
        {code: "S04", name: "Kyopolou with Bruschetta and Walnuts", desc: "traditional roasted eggplant and pepper spread, served with bruschetta", eur: 5.06, bgn: 9.90, weight: "250 g"},
        {code: "S05", name: "Bruschetta with Iberico Lard and Cherry Tomatoes", desc: "toasted bread with cured Iberico lard and cherry tomatoes", eur: 6.08, bgn: 11.90, weight: "250 g"},
        {code: "S06", name: "Bumbar", desc: "traditional grilled offal sausage with rice and spices", eur: 6.60, bgn: 12.90, weight: "250 g"},
        {code: "S07", name: "Stuffed Cabbage Rolls", desc: "sauerkraut cabbage rolls filled with minced meat and rice", eur: 6.44, bgn: 12.60, weight: "250 g"},
        {code: "S08", name: "Homemade Sudzhuk with Fermented Vegetables", desc: "homemade fresh grilled sudzhuk, served with fermented vegetables", eur: 9.00, bgn: 17.60, weight: "450 g"},
        {code: "S09", name: "Retro Mixed Meatballs", desc: "three meatballs made from pork, lamb and beef, homemade lyutenitsa, fermented vegetables and fried potatoes", eur: 8.13, bgn: 15.90, weight: "450 g"},
        {code: "S10", name: "Grilled Pork Belly Slices", desc: "grilled pork belly, homemade lyutenitsa, fermented vegetables and hot chili pepper", eur: 8.08, bgn: 15.80, weight: "400 g"},
        {code: "S11", name: "Kachamak with Egg, Sudzhuk and Cheese", desc: "traditional cornmeal porridge (polenta-style) with egg, sudzhuk and white cheese", eur: 7.11, bgn: 13.90, weight: "450 g"},
        {code: "S12", name: "Grilled Pork Ears", desc: "grilled pork ears", eur: 7.06, bgn: 13.80, weight: "250 g"},
        {code: "S13", name: "Pork Shank with Trotter", desc: "slow-cooked pork shank and pork trotter, caramelized onions and beans", eur: 8.64, bgn: 16.90, weight: "350 g"},
        {code: "S14", name: "Slow-Roasted Pork Belly", desc: "oven-roasted pork belly with rustic potatoes and salad", eur: 11.20, bgn: 21.90, weight: "450 g"},
        {code: "S15", name: "Roasted Pork Shank", desc: "roasted pork shank with rustic potatoes and salad", eur: 12.73, bgn: 24.90, weight: "890 g"},
        {code: "S16", name: "Pork Shank with Sauerkraut and Rice", desc: "pork shank cooked with sauerkraut and rice", eur: 9.15, bgn: 17.90, weight: "450 g"}
      ]
    },
	{
      id: "fish",
      label: "Fish & Seafood",
      items: [
        {code: "F01", name: "Tarama", desc: "classic fish roe spread with red onion and flatbread", eur: 5.57, bgn: 10.90, weight: "180/100 g"},
        {code: "F02", name: "Tuna Salad", desc: "lettuce, tomatoes, canned tuna, sweet corn and lemon", eur: 7.10, bgn: 13.90, weight: "400 g"},
        {code: "F03", name: "Lightly Cured Anchovy Fillet", desc: "cured anchovy fillet, olive oil, onion, lemon and toasted bread", eur: 5.27, bgn: 10.30, weight: "130 g"},
        {code: "F04", name: "Meze Platter for Sharing", desc: "tzatziki, tyrokafteri, tarama, olives, cured anchovy and flatbread", eur: 7.87, bgn: 15.40, weight: "350 g"},
        {code: "F05", name: "Greek-Style Shrimp", desc: "shrimp sautéed with garlic and ouzo", eur: 8.64, bgn: 16.90, weight: "200 g"},
        {code: "F06", name: "Shrimp Saganaki", desc: "shrimp cooked with tomatoes, herbs and cheese", eur: 9.00, bgn: 17.60, weight: "350 g"},
        {code: "F07", name: "Sautéed Mussels", desc: "mussels sautéed with butter, spring onion, garlic, dill and herbs", eur: 7.06, bgn: 13.80, weight: "400 g"},
        {code: "F08", name: "Mussels in Shell", desc: "steamed mussels", eur: 7.06, bgn: 13.80, weight: "500 g"},
        {code: "F09", name: "Mussels Saganaki", desc: "mussels cooked with tomatoes, herbs and cheese", eur: 8.59, bgn: 16.80, weight: "350 g"},
        {code: "F10", name: "Grilled Calamari", desc: "grilled calamari", eur: 11.04, bgn: 21.60, weight: "350 g"},
        {code: "F11", name: "Fried Calamari", desc: "fried calamari", eur: 11.04, bgn: 21.60, weight: "350 g"},
        {code: "F12", name: "Fried Horse Mackerel", desc: "fried horse mackerel", eur: 6.95, bgn: 13.60, weight: "250 g"},
        {code: "F13", name: "Grilled Horse Mackerel", desc: "grilled horse mackerel", eur: 6.95, bgn: 13.60, weight: "250 g"},
        {code: "F14", name: "Fried Anchovies", desc: "fried anchovies", eur: 6.95, bgn: 13.60, weight: "250 g"},
        {code: "F15", name: "Fried Sardines", desc: "fried sardines", eur: 6.95, bgn: 13.60, weight: "250 g"},
        {code: "F16", name: "Grilled Sardines", desc: "grilled sardines", eur: 6.95, bgn: 13.60, weight: "250 g"},
        {code: "F17", name: "Grilled Trout", desc: "whole trout, grilled", eur: 10.17, bgn: 19.90, weight: "400 g"},
        {code: "F18", name: "Grilled Sea Bass", desc: "whole sea bass, grilled", eur: 11.71, bgn: 22.90, weight: "500 g"},
        {code: "F19", name: "Grilled Sea Bream", desc: "whole sea bream, grilled", eur: 11.71, bgn: 22.90, weight: "500 g"},
        {code: "F20", name: "Octopus with Cherry Tomatoes and Olives", desc: "pan-sautéed octopus with cherry tomatoes, olives and vegetables", eur: 17.90, bgn: 35.00, weight: "150/150 g"},
        {code: "F21", name: "Linguine with Seafood", desc: "linguine pasta with shrimp, mussels and calamari in tomato sauce", eur: 8.95, bgn: 17.50, weight: "400 g"},
        {code: "F22", name: "Frog Legs Provençal", desc: "frog legs sautéed with garlic, butter and parsley", eur: 8.85, bgn: 17.30, weight: "6 pcs"},
        {code: "F23", name: "Breaded Frog Legs", desc: "breaded and fried frog legs", eur: 8.54, bgn: 16.70, weight: "5 pcs"}
      ]
    },
	{
      id: "salads",
      label: "Salads",
      items: [
        {code: "SA01", name: "Shopska Salad", desc: "tomatoes, cucumbers, white cheese", eur: 5.37, bgn: 10.50, weight: "400 g"},
        {code: "SA02", name: "Tomato Salad", desc: "fresh tomatoes", eur: 5.01, bgn: 9.80, weight: "330 g"},
        {code: "SA03", name: "Tomato Salad with White Cheese", desc: "tomatoes and Bulgarian white cheese", eur: 5.32, bgn: 10.40, weight: "380 g"},
        {code: "SA04", name: "Tomato Salad with Katak", desc: "tomatoes with katak (Bulgarian dairy spread)", eur: 5.42, bgn: 10.60, weight: "400 g"},
        {code: "SA05", name: "Tomatoes and Roasted Peppers with Katak", desc: "tomatoes, roasted peppers and katak", eur: 5.98, bgn: 11.70, weight: "450 g"},
        {code: "SA06", name: "Tomatoes, Roasted Peppers and White Cheese", desc: "tomatoes, roasted peppers and white cheese", eur: 5.98, bgn: 11.70, weight: "400 g"},
        {code: "SA07", name: "Cucumber Salad", desc: "fresh cucumbers", eur: 5.01, bgn: 9.80, weight: "330 g"},
        {code: "SA08", name: "Roasted Peppers with Onion", desc: "roasted peppers and onion", eur: 5.06, bgn: 9.90, weight: "280 g"},
        {code: "SA09", name: "Roasted Peppers with Garlic", desc: "roasted peppers and garlic", eur: 5.06, bgn: 9.90, weight: "260 g"},
        {code: "SA10", name: "Cabbage and Carrot Salad", desc: "white cabbage and carrots", eur: 4.55, bgn: 8.90, weight: "300 g"},
        {code: "SA11", name: "Katak with Roasted Peppers", desc: "katak (Bulgarian dairy spread) with roasted peppers", eur: 5.42, bgn: 10.60, weight: "200 g"},
        {code: "SA12", name: "Country-Style Salad", desc: "tomatoes, cucumbers, roasted pepper, onion and white cheese", eur: 5.57, bgn: 10.90, weight: "450 g"},
        {code: "SA13", name: "Shepherd's Salad", desc: "tomatoes, cucumbers, pepper, onion, ham, sweet corn, yellow cheese and white cheese", eur: 6.75, bgn: 13.20, weight: "500 g"},
        {code: "SA14", name: "Greek Salad", desc: "tomatoes, cucumbers, roasted peppers, onion, white cheese, olives, oregano and olive oil", eur: 5.88, bgn: 11.50, weight: "430 g"},
        {code: "SA15", name: "Caesar Salad", desc: "iceberg lettuce, arugula, cherry tomatoes, chicken fillet, parmesan, croutons and Caesar dressing", eur: 7.31, bgn: 14.30, weight: "350 g"},
        {code: "SA16", name: "Balkan Grilled Vegetable Salad", desc: "tomatoes, roasted pepper, grilled zucchini and eggplant, sheep's cheese, pesto sauce", eur: 7.06, bgn: 13.80, weight: "350 g"},
        {code: "SA17", name: "Caprese Salad", desc: "tomatoes, mozzarella, pesto sauce and olive oil", eur: 7.10, bgn: 13.90, weight: "350 g"},
        {code: "SA18", name: "Tuna Salad", desc: "lettuce, tomatoes, canned tuna, sweet corn and lemon", eur: 7.10, bgn: 13.90, weight: "350 g"},
        {code: "SA19", name: "Green Salad with Egg", desc: "lettuce, cucumbers, spring onion and egg", eur: 5.62, bgn: 11.00, weight: "350 g"},
        {code: "SA20", name: "Dairy Salad", desc: "yogurt, cucumbers, garlic and walnuts", eur: 5.06, bgn: 9.90, weight: "200 g"},
        {code: "SA21", name: "Egg and Potato Salad", desc: "grated egg and potatoes, blended with mayonnaise and mustard", eur: 5.06, bgn: 9.90, weight: "200 g"},
        {code: "SA22", name: "Winter Tomato", desc: "roasted tomato, katak, olives, walnuts and wild garlic pesto", eur: 6.60, bgn: 12.90, weight: "350 g"},
        {code: "SA23", name: "Spinach & Blue Cheese Salad", desc: "baby spinach, blue cheese, sun-dried tomatoes, walnuts and dressing", eur: 7.10, bgn: 13.90, weight: "300 g"},
        {code: "SA24", name: "Bean and Mushroom Salad", desc: "beans, mushrooms, olives, roasted pepper and pickles", eur: 5.57, bgn: 10.90, weight: "350 g"},
        {code: "SA25", name: "King Edward Salad", desc: "white cheese, yellow cheese, egg, mayonnaise and pickles", eur: 5.57, bgn: 10.90, weight: "300 g"},
        {code: "SA26", name: "Tomato Salad with Blue Cheese", desc: "tomatoes, blue cheese, white cheese, olive oil and oregano", eur: 6.39, bgn: 12.50, weight: "320 g"},
        {code: "SA27", name: "Plovdiv-Style Marinated Vegetables", desc: "marinated eggplant, zucchini and peppers, olives and sheep's cheese", eur: 7.98, bgn: 15.60, weight: "400 g"},
        {code: "SA28", name: "Zhekova Salad", desc: "tomatoes, roasted pepper, onion and baked white cheese", eur: 5.98, bgn: 11.70, weight: "400 g"},
        {code: "SA29", name: "Ouzo Meze Platter", desc: "tomato, sheep's cheese, olives, kyopolou, pork fillet, bruschetta and hot chili pepper", eur: 7.72, bgn: 15.10, weight: "450 g"},
        {code: "SA30", name: "Fermented Vegetables", desc: "traditional fermented vegetables", eur: 5.22, bgn: 10.20, weight: "300 g"},
        {code: "SA31", name: "Kalamata Olives with Onion", desc: "Kalamata olives and onion", eur: 5.06, bgn: 9.90, weight: "220 g"},
        {code: "SA32", name: "Boiled Potatoes with Onion", desc: "boiled potatoes and onion", eur: 4.60, bgn: 9.00, weight: "400 g"}
      ]
    },
	{
      id: "appetizers",
      label: "Spreads & Meze",
      items: [
        {code: "RZ01", name: "Tzatziki", desc: "", eur: 5.06, bgn: 9.90, weight: "200 g"},
        {code: "RZ02", name: "Tyrokafteri", desc: "spicy cheese spread with chili peppers", eur: 5.06, bgn: 9.90, weight: "150 g"},
        {code: "RZ03", name: "Katak", desc: "katak (Bulgarian dairy spread)", eur: 5.06, bgn: 9.90, weight: "200 g"},
        {code: "RZ04", name: "Hummus with Bruschetta", desc: "", eur: 5.06, bgn: 9.90, weight: "250 g"},
        {code: "RZ05", name: "Kyopolou with Bruschetta and Walnuts", desc: "traditional roasted eggplant and pepper spread", eur: 5.06, bgn: 9.90, weight: "250 g"},
        {code: "RZ06", name: "Tarama with Greek Flatbread", desc: "", eur: 5.57, bgn: 10.90, weight: "180/100 g"},
        {code: "RZ07", name: "Ouzo Meze Platter", desc: "tomato, white cheese, olives, kyopolou, pork fillet and bruschetta", eur: 7.72, bgn: 15.10, weight: "450 g"},
        {code: "RZ08", name: "Lightly Cured Anchovy Fillet", desc: "cured anchovy fillet with onion, olive oil and lemon", eur: 5.27, bgn: 10.30, weight: "130 g"},
        {code: "RZ09", name: "Paprika u Pavlak", desc: "spicy cream spread with chili peppers", eur: 5.06, bgn: 9.90, weight: "200 g"},
        {code: "RZ10", name: "Meze Platter for Sharing", desc: "tzatziki, tyrokafteri, tarama, olives, cured anchovy and Greek flatbread", eur: 7.87, bgn: 15.40, weight: "350 g"}
      ]
    },
	{
      id: "starters-veg",
      label: "Meat-Free Starters",
      items: [
        {code: "PB01", name: "Cheese-Stuffed Fried Peppers", desc: "", eur: 6.08, bgn: 11.90, weight: "2 pcs"},
        {code: "PB02", name: "Peppers in Tomato Sauce", desc: "", eur: 6.60, bgn: 12.90, weight: "400 g"},
        {code: "PB03", name: "Stuffed Mushrooms", desc: "mushrooms, white cheese, yellow cheese and garlic", eur: 6.60, bgn: 12.90, weight: "250 g"},
        {code: "PB04", name: "Fried Zucchini with Garlic Yogurt Sauce", desc: "", eur: 6.44, bgn: 12.60, weight: "300 g"},
        {code: "PB05", name: "Eggplant in Tomato Sauce", desc: "", eur: 6.60, bgn: 12.90, weight: "400 g"},
        {code: "PB06", name: "Vegetables in Creamy Cheese Sauce", desc: "broccoli, cauliflower, mushrooms, onion, sweet corn, peas, carrots, cream and processed cheese", eur: 6.60, bgn: 12.90, weight: "500 g"},
        {code: "PB07", name: "Grilled Vegetables", desc: "zucchini, eggplant, potatoes, mushrooms, onion and peppers", eur: 6.60, bgn: 12.90, weight: "500 g"},
        {code: "PB08", name: "Broccoli in Butter", desc: "", eur: 6.08, bgn: 11.90, weight: "300 g"},
        {code: "PB09", name: "Broccoli with Melted Cheese and Cream", desc: "broccoli, cream, processed cheese and yellow cheese", eur: 6.60, bgn: 12.90, weight: "400 g"},
        {code: "PB10", name: "Breaded Broccoli", desc: "", eur: 6.49, bgn: 12.70, weight: "350 g"},
        {code: "PB11", name: "Fried Spinach Patties", desc: "", eur: 6.60, bgn: 12.90, weight: "500 g"},
        {code: "PB12", name: "Fried Zucchini Patties", desc: "", eur: 6.60, bgn: 12.90, weight: "500 g"},
        {code: "PB13", name: "Shopska-Style Baked Cheese", desc: "white cheese, tomato, roasted pepper and egg", eur: 5.57, bgn: 10.90, weight: "250 g"},
        {code: "PB14", name: "Pan-Seared Cheese with Honey and Walnuts", desc: "baked white cheese with honey and walnuts", eur: 5.57, bgn: 10.90, weight: "230 g"},
        {code: "PB15", name: "Smoked Cheese Bites in Cornflakes", desc: "served with blueberry jam", eur: 6.08, bgn: 11.90, weight: "250 g"},
        {code: "PB16", name: "Beer-Battered White Cheese", desc: "served with blueberry jam", eur: 6.80, bgn: 13.30, weight: "250 g"},
        {code: "PB17", name: "Beer-Battered Yellow Cheese", desc: "", eur: 6.80, bgn: 13.30, weight: "250 g"},
        {code: "PB18", name: "Breaded Yellow Cheese", desc: "", eur: 6.49, bgn: 12.70, weight: "200 g"},
        {code: "PB19", name: "Pan-Seared Yellow Cheese", desc: "", eur: 6.39, bgn: 12.50, weight: "200 g"},
        {code: "PB20", name: "Baked Potatoes with Mixed Cheeses", desc: "potatoes, cream, processed cheese, blue cheese, white cheese and yellow cheese", eur: 6.60, bgn: 12.90, weight: "500 g"},
        {code: "PB21", name: "Fresh-Cut Fried Potatoes", desc: "", eur: 3.83, bgn: 7.50, weight: "500 g"},
        {code: "PB22", name: "Fresh-Cut Fried Potatoes with Cheese", desc: "", eur: 4.09, bgn: 8.00, weight: "550 g"},
        {code: "PB23", name: "French Fries", desc: "", eur: 3.83, bgn: 7.50, weight: "350 g"},
        {code: "PB24", name: "French Fries with Cheese", desc: "", eur: 4.09, bgn: 8.00, weight: "400 g"},
        {code: "PB25", name: "Vegetable and Egg Scramble", desc: "eggs, white cheese, peppers, onion and tomato", eur: 5.73, bgn: 11.20, weight: "350 g"}
      ]
    },
	{
      id: "starters-meat",
      label: "Meat Starters",
      items: [
        {code: "PM01", name: "Stuffed Cabbage Rolls", desc: "", eur: 6.14, bgn: 12.60, weight: "250 g"},
        {code: "PM02", name: "Stuffed Vine Leaves", desc: "", eur: 6.14, bgn: 12.60, weight: "250 g"},
        {code: "PM03", name: "Sautéed Veal Tongue in Butter", desc: "", eur: 8.13, bgn: 15.90, weight: "180 g"},
        {code: "PM04", name: "Breaded Veal Tongue", desc: "", eur: 8.59, bgn: 16.80, weight: "220 g"},
        {code: "PM05", name: "Baked Veal Tongue with Mixed Cheeses", desc: "veal tongue, processed cheese, blue cheese, white cheese and cream", eur: 8.39, bgn: 16.40, weight: "250 g"},
        {code: "PM06", name: "Tripe in Butter", desc: "", eur: 6.60, bgn: 12.90, weight: "200 g"},
        {code: "PM07", name: "Tripe with Mushrooms and Yellow Cheese", desc: "", eur: 7.52, bgn: 14.70, weight: "300 g"},
        {code: "PM08", name: "Slow-Cooked Lamb Head", desc: "", eur: 8.23, bgn: 16.10, weight: "1 pc"},
        {code: "PM09", name: "Lamb Offal in Butter", desc: "", eur: 6.80, bgn: 13.30, weight: "180 g"},
        {code: "PM10", name: "Mixed Offal Baked in Clay Pot", desc: "pork liver, veal tongue, veal tripe and yellow cheese", eur: 6.22, bgn: 16.00, weight: "350 g"},
        {code: "PM11", name: "Chicken Livers in Butter", desc: "", eur: 6.60, bgn: 12.90, weight: "300 g"},
        {code: "PM12", name: "Country-Style Chicken Livers", desc: "chicken livers with onion, peppers, mushrooms and tomatoes", eur: 7.52, bgn: 14.70, weight: "450 g"},
        {code: "PM13", name: "Fried Pork Liver", desc: "", eur: 6.60, bgn: 12.90, weight: "250 g"},
        {code: "PM14", name: "Breaded Chicken Gizzards", desc: "", eur: 6.60, bgn: 12.90, weight: "300 g"},
        {code: "PM15", name: "Chicken Hearts in Butter", desc: "", eur: 6.60, bgn: 12.90, weight: "200 g"},
        {code: "PM16", name: "Chicken Hearts with Onion, Mushrooms and Melted Cheese", desc: "", eur: 7.11, bgn: 13.90, weight: "380 g"},
        {code: "PM17", name: "Chicken Hearts with Mushrooms and Yellow Cheese", desc: "", eur: 7.11, bgn: 13.90, weight: "320 g"},
        {code: "PM18", name: "Mixed Chicken Offal", desc: "chicken livers, hearts, gizzards and yellow cheese", eur: 8.13, bgn: 15.90, weight: "400 g"},
        {code: "PM19", name: "Chicken Bites in Cornflakes", desc: "", eur: 6.60, bgn: 12.90, weight: "300 g"},
        {code: "PM20", name: "Chicken Bites with Sesame", desc: "", eur: 6.60, bgn: 12.90, weight: "300 g"},
        {code: "PM21", name: "Chicken Bites with Honey and Soy Sauce", desc: "", eur: 6.60, bgn: 12.90, weight: "250 g"},
        {code: "PM22", name: "Baked Potatoes with Bacon and Cheese", desc: "potatoes, bacon, cream and yellow cheese", eur: 6.60, bgn: 12.90, weight: "500 g"},
        {code: "PM23", name: "Chicken Rockers Meze", desc: "chicken fillet sautéed with mushrooms, garlic and soy sauce", eur: 6.60, bgn: 12.90, weight: "300 g"},
        {code: "PM24", name: "Pork Rockers Meze", desc: "pork fillet sautéed with mushrooms, garlic and soy sauce", eur: 7.16, bgn: 14.00, weight: "300 g"},
        {code: "PM25", name: "Chicken Wings in Soy Sauce", desc: "", eur: 6.90, bgn: 13.50, weight: "350 g"},
        {code: "PM26", name: "Chicken Gizzards in Butter", desc: "", eur: 6.44, bgn: 12.60, weight: "230 g"},
        {code: "PM27", name: "Thracian-Style Baked Cheese with Lukanka", desc: "white cheese, tomato, roasted pepper, egg and lukanka", eur: 6.39, bgn: 12.50, weight: "330 g"},
        {code: "PM28", name: "Bumbar", desc: "traditional grilled offal sausage with rice and spices", eur: 6.60, bgn: 12.90, weight: "250 g"}
      ]
    },
	{
      id: "pasta",
      label: "Pasta & Risotto",
      items: [
        {code: "PR01", name: "Wild Mushroom Risotto", desc: "risotto with porcini and mixed mushrooms, onion and parmesan", eur: 8.13, bgn: 15.90, weight: "400 g"},
        {code: "PR02", name: "Chicken, Spinach & Blue Cheese Risotto", desc: "risotto with chicken fillet, spinach and blue cheese", eur: 8.13, bgn: 15.90, weight: "400 g"},
        {code: "PR03", name: "Vegetable Risotto", desc: "risotto with peppers, carrots, celery, broccoli and zucchini", eur: 8.13, bgn: 15.90, weight: "400 g"},
        {code: "PR04", name: "Spaghetti Bolognese", desc: "spaghetti with classic meat sauce", eur: 8.28, bgn: 16.20, weight: "400 g"},
        {code: "PR05", name: "Spaghetti Carbonara", desc: "", eur: 8.28, bgn: 16.20, weight: "400 g"}
      ]
    },
	{
      id: "mains",
      label: "Main Courses",
      items: [
        {code: "M01", name: "Chicken Fillet with Garlic and White Wine", desc: "chicken fillet, garlic, white wine and sautéed potatoes", eur: 7.57, bgn: 14.80, weight: "250 g"},
        {code: "M02", name: "Baked Chicken Fillet with Tomatoes and Cheese", desc: "chicken fillet, tomatoes, yellow cheese and basil", eur: 7.67, bgn: 15.00, weight: "350 g"},
        {code: "M03", name: "Chicken Kavarma", desc: "chicken fillet with mushrooms, onion, peppers and tomatoes", eur: 8.13, bgn: 15.90, weight: "400 g"},
        {code: "M04", name: "Chicken Fillet with Mushrooms", desc: "", eur: 7.62, bgn: 14.90, weight: "350 g"},
        {code: "M05", name: "Chicken Steak with Blue Cheese Sauce", desc: "chicken steak, blue cheese, cream and sautéed potatoes", eur: 8.13, bgn: 15.90, weight: "500 g"},
        {code: "M06", name: "Chicken with Onion, Mushrooms and Tomatoes", desc: "chicken steak with onion, mushrooms, garlic, tomatoes and spices", eur: 7.87, bgn: 15.40, weight: "350 g"},
        {code: "M07", name: "Chicken with Sautéed Vegetables", desc: "chicken fillet with carrots, cucumber, peppers, mushrooms and eggplant", eur: 7.62, bgn: 14.90, weight: "400 g"},
        {code: "M08", name: "Chicken with Broccoli in Cream Sauce", desc: "", eur: 7.62, bgn: 14.90, weight: "380 g"},
        {code: "M09", name: "Slow-Roasted Pork Knuckle", desc: "", eur: 12.73, bgn: 24.90, weight: "800 g"},
        {code: "M10", name: "Kateno Meze", desc: "mixed pork and chicken with onion, mushrooms and pickles", eur: 8.03, bgn: 15.70, weight: "400 g"},
        {code: "M11", name: "Pan-Seared Pork Loin", desc: "", eur: 7.11, bgn: 13.90, weight: "200 g"},
        {code: "M12", name: "Pork Kavarma", desc: "pork with onion, mushrooms, peppers and tomatoes", eur: 8.13, bgn: 15.90, weight: "400 g"},
        {code: "M13", name: "Roasted Lamb with Potatoes and Green Salad", desc: "", eur: 16.87, bgn: 33.00, weight: "450 g"},
        {code: "M14", name: "Pork Tenderloin with Honey-Garlic Sauce", desc: "", eur: 7.93, bgn: 15.50, weight: "300 g"},
        {code: "M15", name: "Young Veal with Rustic Potatoes and Green Salad", desc: "", eur: 12.73, bgn: 24.90, weight: "400 g"},
        {code: "M16", name: "Pork Fillet with Mushrooms", desc: "", eur: 7.93, bgn: 15.50, weight: "350 g"},
        {code: "M17", name: "Pork with Onion and Spices", desc: "pork neck sautéed with onion, spices and hot chili pepper", eur: 7.62, bgn: 14.90, weight: "350 g"},
        {code: "M18", name: "Pork Neck Steak with Sautéed Vegetables", desc: "pork neck with zucchini, eggplant, mushrooms and peppers", eur: 8.13, bgn: 15.90, weight: "450 g"},
        {code: "M19", name: "Slow-Roasted Pork Belly", desc: "roasted pork belly with rustic potatoes and salad", eur: 11.20, bgn: 21.90, weight: "450 g"}
      ]
    },
	{
      id: "grill",
      label: "Grill",
      items: [
        {code: "G01", name: "Retro Mixed Meatballs", desc: "three grilled meatballs with pork, lamb and beef, served with fried potatoes, seasonal salad and homemade lyutenitsa", eur: 8.13, bgn: 15.90, weight: "300/250 g"},
        {code: "G02", name: "Grilled Pork Belly", desc: "grilled pork belly slices with homemade lyutenitsa, seasonal salad and hot chili pepper", eur: 8.08, bgn: 15.80, weight: "250/250 g"},
        {code: "G03", name: "Grilled Chicken Fillet or Steak", desc: "chicken fillet (breast) or chicken steak (thigh)", eur: 7.06, bgn: 13.80, weight: "220/250 g"},
        {code: "G04", name: "Black Angus Beef Meatballs on Skewers", desc: "two skewers, fresh salad, rustic potatoes and chimichurri sauce", eur: 8.64, bgn: 16.90, weight: "240/200 g"},
        {code: "G05", name: "Grilled Chicken Wings", desc: "", eur: 6.90, bgn: 13.50, weight: "350 g"},
        {code: "G06", name: "Grilled Pork Ribs", desc: "", eur: 9.63, bgn: 18.90, weight: "500 g"},
        {code: "G07", name: "Grilled Pork Neck", desc: "", eur: 7.26, bgn: 14.20, weight: "250 g"},
        {code: "G08", name: "Grilled Pork Tenderloin", desc: "", eur: 8.08, bgn: 15.80, weight: "230 g"},
        {code: "G09", name: "Grilled Pork Loin", desc: "", eur: 7.11, bgn: 13.90, weight: "200 g"},
        {code: "G10", name: "Grilled Duck Hearts", desc: "", eur: 7.62, bgn: 14.90, weight: "200 g"}
      ]
    },
	{
      id: "sides",
      label: "Sides, Bread & Add-ons",
      items: [
        {code: "KJ01", name: "Tomato & Cucumber Side", desc: "", eur: 2.20, bgn: 4.30, weight: "160 g"},
        {code: "KJ02", name: "Boiled Potatoes with Onion (Side)", desc: "", eur: 2.05, bgn: 4.00, weight: "250 g"},
        {code: "KJ03", name: "Fried Potatoes (Side)", desc: "", eur: 2.05, bgn: 4.00, weight: "200 g"},
        {code: "KJ04", name: "Fried Potatoes with White Cheese (Side)", desc: "", eur: 2.20, bgn: 4.30, weight: "230 g"},
        {code: "KJ05", name: "Cabbage & Carrot Salad (Side)", desc: "", eur: 2.05, bgn: 4.00, weight: "150 g"},
        {code: "KJ06", name: "Slice of Bread", desc: "", eur: 0.36, bgn: 0.70, weight: "1 pc"},
        {code: "KJ07", name: "Garlic Bread Slice", desc: "", eur: 0.77, bgn: 1.50, weight: "1 pc"},
        {code: "KJ08", name: "Homemade Bread", desc: "", eur: 3.53, bgn: 6.90, weight: "1 pc"},
        {code: "KJ09", name: "Garlic Flatbread", desc: "", eur: 2.15, bgn: 4.20, weight: "1 pc"},
        {code: "KJ10", name: "Flatbread with White Cheese", desc: "", eur: 2.45, bgn: 4.80, weight: "1 pc"},
        {code: "KJ11", name: "Flatbread with Yellow Cheese", desc: "", eur: 2.66, bgn: 5.20, weight: "1 pc"},
        {code: "KJ12", name: "Mixed Flatbread", desc: "", eur: 2.86, bgn: 5.60, weight: "1 pc"},
        {code: "KJ13", name: "Hot Chili Pepper", desc: "", eur: 0.61, bgn: 1.20, weight: "1 pc"},
        {code: "KJ14", name: "Sauce", desc: "", eur: 1.02, bgn: 2.00, weight: "50 ml"},
        {code: "KJ15", name: "Lyutenitsa", desc: "", eur: 1.53, bgn: 3.00, weight: "60 g"},
        {code: "KJ16", name: "Ketchup / Mustard / Yogurt", desc: "", eur: 1.02, bgn: 2.00, weight: "50 ml"},
        {code: "KJ17", name: "Egg", desc: "", eur: 1.02, bgn: 2.00, weight: "1 pc"},
        {code: "KJ18", name: "Lemon", desc: "", eur: 1.02, bgn: 2.00, weight: "1/2 pc"},
        {code: "KJ19", name: "Homemade Sudzhuk / Pork Fillet", desc: "", eur: 2.81, bgn: 5.50, weight: "50 g"},
        {code: "KJ20", name: "Cow's White Cheese", desc: "", eur: 1.48, bgn: 2.90, weight: "50 g"},
        {code: "KJ21", name: "Sheep / Goat Cheese", desc: "", eur: 2.30, bgn: 4.50, weight: "50 g"},
        {code: "KJ22", name: "Blue Cheese", desc: "", eur: 2.56, bgn: 5.00, weight: "50 g"},
        {code: "KJ23", name: "Yellow Cheese", desc: "", eur: 2.30, bgn: 4.50, weight: "50 g"}
      ]
    },
	{
      id: "desserts",
      label: "Desserts",
      items: [
        {code: "D01", name: "Ice Cream", desc: "1 serving", eur: 2.91, bgn: 5.70, weight: "150 g"},
        {code: "D02", name: "Homemade Ice Creams – Assorted Flavors", desc: "house-made ice creams, various flavors", eur: 3.74, bgn: 6.60, weight: "150 g"},
        {code: "D03", name: "Crêpe with Chocolate or Jam", desc: "", eur: 3.02, bgn: 5.90, weight: "1 pc"},
        {code: "D04", name: "Crêpe with Honey and Walnuts", desc: "", eur: 3.02, bgn: 5.90, weight: "1 pc"},
        {code: "D05", name: "Apple Pie", desc: "", eur: 3.02, bgn: 5.90, weight: "1 pc"},
        {code: "D06", name: "Chocolate Lava Cake with Ice Cream", desc: "", eur: 3.17, bgn: 6.20, weight: "1 pc"},
        {code: "D07", name: "Dessert of the Day", desc: "ask your server", eur: 0, bgn: 0, weight: ""}
      ]
    },
	{
      id: "soft-drinks",
      label: "Soft Drinks",
      items: [
        {code: "BN01", name: "Coca-Cola", desc: "", eur: 2.05, bgn: 4.00, weight: "250 ml"},
        {code: "BN02", name: "Fanta", desc: "", eur: 2.05, bgn: 4.00, weight: "250 ml"},
        {code: "BN03", name: "Sprite", desc: "", eur: 2.05, bgn: 4.00, weight: "250 ml"},
        {code: "BN04", name: "Tonic", desc: "", eur: 2.05, bgn: 4.00, weight: "250 ml"},
        {code: "BN05", name: "Schweppes", desc: "", eur: 2.05, bgn: 4.00, weight: "250 ml"},
        {code: "BN06", name: "Iced Tea", desc: "", eur: 2.05, bgn: 4.00, weight: "250 ml"},
        {code: "BN07", name: "Sparkling Water", desc: "", eur: 1.54, bgn: 3.00, weight: "330 ml"},
        {code: "BN08", name: "Mineral Water (Still)", desc: "", eur: 1.54, bgn: 3.00, weight: "500 ml"},
        {code: "BN09", name: "Mineral Water (Still)", desc: "", eur: 2.56, bgn: 5.00, weight: "1.5 l"},
        {code: "BN10", name: "Homemade Tomato Juice", desc: "", eur: 2.05, bgn: 4.00, weight: "250 ml"},
        {code: "BN11", name: "Ayran (Yogurt Drink)", desc: "", eur: 1.54, bgn: 3.00, weight: "250 ml"},
        {code: "BN12", name: "Ayran (Yogurt Drink)", desc: "", eur: 2.05, bgn: 4.00, weight: "500 ml"},
        {code: "BN13", name: "Homemade Lavender Lemonade with Honey", desc: "", eur: 2.56, bgn: 5.00, weight: "250 ml"},
        {code: "BN14", name: "Homemade Lavender Lemonade with Honey", desc: "", eur: 4.09, bgn: 8.00, weight: "500 ml"},
        {code: "BN15", name: "Cappy Juice", desc: "", eur: 2.05, bgn: 4.00, weight: "250 ml"},
        {code: "BN16", name: "Fresh Juice", desc: "", eur: 3.58, bgn: 7.00, weight: "250 ml"},
        {code: "BN17", name: "Espresso", desc: "", eur: 1.54, bgn: 3.00, weight: "60 ml"},
        {code: "BN18", name: "Tea", desc: "", eur: 1.54, bgn: 3.00, weight: "200 ml"},
        {code: "BN19", name: "Honey / Cream / Milk", desc: "add-on", eur: 0.82, bgn: 1.60, weight: ""}
      ]
    },
	{
      id: "alcohol",
      label: "Alcohol",
      items: [
        {code: "AN01", name: "Peshterska Rakia", desc: "", eur: 2.56, bgn: 5.00, weight: "50 ml"},
        {code: "AN02", name: "Karnobatska Rakia", desc: "", eur: 2.56, bgn: 5.00, weight: "50 ml"},
        {code: "AN03", name: "Slivenska Rakia", desc: "", eur: 2.56, bgn: 5.00, weight: "50 ml"},
        {code: "AN04", name: "Troyanska Plum Rakia", desc: "", eur: 2.56, bgn: 5.00, weight: "50 ml"},
        {code: "AN05", name: "Muskatova Rakia", desc: "", eur: 2.56, bgn: 5.00, weight: "50 ml"},
        {code: "AN06", name: "Apricot Rakia", desc: "", eur: 2.56, bgn: 5.00, weight: "50 ml"},
        {code: "AN07", name: "Pear Rakia", desc: "", eur: 2.56, bgn: 5.00, weight: "50 ml"},
        {code: "AN08", name: "Grape Rakia", desc: "", eur: 2.56, bgn: 5.00, weight: "50 ml"},
        {code: "AN09", name: "Aged Rakia", desc: "", eur: 3.07, bgn: 6.00, weight: "50 ml"},
        {code: "AN10", name: "Barrel-Aged Rakia", desc: "", eur: 3.58, bgn: 7.00, weight: "50 ml"},
        {code: "AN11", name: "Homemade Rakia", desc: "", eur: 2.56, bgn: 5.00, weight: "50 ml"},
        {code: "AN12", name: "Premium Rakia", desc: "", eur: 3.58, bgn: 7.00, weight: "50 ml"},
        {code: "AN13", name: "Ouzo 12", desc: "", eur: 2.56, bgn: 5.00, weight: "50 ml"},
        {code: "AN14", name: "Plomari Ouzo", desc: "", eur: 2.56, bgn: 5.00, weight: "50 ml"},
        {code: "AN15", name: "Barbayanni Ouzo", desc: "", eur: 2.56, bgn: 5.00, weight: "50 ml"},
        {code: "AN16", name: "Vantana Ouzo", desc: "", eur: 2.56, bgn: 5.00, weight: "50 ml"},
        {code: "AN17", name: "Mavrommati Ouzo", desc: "", eur: 2.56, bgn: 5.00, weight: "50 ml"},
        {code: "AN18", name: "Matarelli Ouzo", desc: "", eur: 2.56, bgn: 5.00, weight: "50 ml"},
        {code: "AN19", name: "Mini Ouzo", desc: "", eur: 2.56, bgn: 5.00, weight: "50 ml"},
        {code: "AN20", name: "Mastika", desc: "", eur: 2.56, bgn: 5.00, weight: "50 ml"},
        {code: "AN21", name: "Mastika Premium", desc: "", eur: 3.07, bgn: 6.00, weight: "50 ml"},
        {code: "AN22", name: "Mastika with Honey", desc: "", eur: 3.07, bgn: 6.00, weight: "50 ml"},
        {code: "AN23", name: "Mastika Aged", desc: "", eur: 3.58, bgn: 7.00, weight: "50 ml"},
        {code: "AN24", name: "Mint Liqueur", desc: "", eur: 2.05, bgn: 4.00, weight: "50 ml"},
        {code: "AN25", name: "Baileys", desc: "", eur: 2.56, bgn: 5.00, weight: "50 ml"},
        {code: "AN26", name: "Jägermeister", desc: "", eur: 2.56, bgn: 5.00, weight: "50 ml"},
        {code: "AN27", name: "Absolut Vodka", desc: "", eur: 2.56, bgn: 5.00, weight: "50 ml"},
        {code: "AN28", name: "Finlandia Vodka", desc: "", eur: 2.56, bgn: 5.00, weight: "50 ml"},
        {code: "AN29", name: "Beluga Vodka", desc: "", eur: 4.60, bgn: 9.00, weight: "50 ml"},
        {code: "AN30", name: "Russian Standard", desc: "", eur: 2.56, bgn: 5.00, weight: "50 ml"},
        {code: "AN31", name: "Grey Goose", desc: "", eur: 4.60, bgn: 9.00, weight: "50 ml"},
        {code: "AN32", name: "Stolichnaya", desc: "", eur: 2.56, bgn: 5.00, weight: "50 ml"},
        {code: "AN33", name: "Belvedere", desc: "", eur: 4.60, bgn: 9.00, weight: "50 ml"},
        {code: "AN34", name: "Smirnoff", desc: "", eur: 2.56, bgn: 5.00, weight: "50 ml"},
        {code: "AN35", name: "Johnnie Walker Red Label", desc: "", eur: 2.56, bgn: 5.00, weight: "50 ml"},
        {code: "AN36", name: "Johnnie Walker Black Label", desc: "", eur: 3.58, bgn: 7.00, weight: "50 ml"},
        {code: "AN37", name: "Savoy Whisky", desc: "", eur: 3.58, bgn: 7.00, weight: "50 ml"},
        {code: "AN38", name: "Jameson", desc: "", eur: 2.56, bgn: 5.00, weight: "50 ml"},
        {code: "AN39", name: "Bushmills", desc: "", eur: 2.56, bgn: 5.00, weight: "50 ml"},
        {code: "AN40", name: "Four Roses", desc: "", eur: 2.56, bgn: 5.00, weight: "50 ml"},
        {code: "AN41", name: "Jack Daniel's", desc: "", eur: 3.07, bgn: 6.00, weight: "50 ml"},
        {code: "AN42", name: "Rum", desc: "", eur: 2.56, bgn: 5.00, weight: "50 ml"},
        {code: "AN43", name: "Pliska Brandy", desc: "", eur: 2.56, bgn: 5.00, weight: "50 ml"},
        {code: "AN44", name: "Imported Cognac", desc: "", eur: 3.58, bgn: 7.00, weight: "50 ml"},
        {code: "AN45", name: "Martini Vermouth", desc: "", eur: 2.56, bgn: 5.00, weight: "50 ml"},
        {code: "AN46", name: "Beefeater Gin", desc: "", eur: 2.56, bgn: 5.00, weight: "50 ml"}
      ]
    },
	{
      id: "beer",
      label: "Beer",
      items: [
        {code: "BV01", name: "Kamenitza Draft", desc: "", eur: 2.20, bgn: 4.30, weight: "330 ml"},
        {code: "BV02", name: "Kamenitza Draft", desc: "", eur: 2.66, bgn: 5.20, weight: "500 ml"},
        {code: "BV03", name: "Madri", desc: "", eur: 2.81, bgn: 5.50, weight: "500 ml"},
        {code: "BV04", name: "Franziskaner", desc: "", eur: 5.22, bgn: 10.20, weight: "500 ml"},
        {code: "BV05", name: "Kamenitza", desc: "", eur: 2.66, bgn: 5.20, weight: "500 ml"},
        {code: "BV06", name: "Burgasko", desc: "", eur: 2.66, bgn: 5.20, weight: "500 ml"},
        {code: "BV07", name: "Stella Artois 0.0", desc: "", eur: 3.07, bgn: 6.00, weight: "330 ml"},
        {code: "BV08", name: "Stella Artois", desc: "", eur: 3.22, bgn: 6.30, weight: "500 ml"},
        {code: "BV09", name: "Staropramen", desc: "", eur: 3.02, bgn: 5.90, weight: "500 ml"},
        {code: "BV10", name: "Leffe Blonde / Brune", desc: "", eur: 4.04, bgn: 7.90, weight: "330 ml"},
        {code: "BV11", name: "Corona Extra", desc: "", eur: 3.48, bgn: 6.80, weight: "330 ml"},
        {code: "BV12", name: "Beck's", desc: "", eur: 2.86, bgn: 5.60, weight: "500 ml"}
      ]
    },
	{
      id: "wine",
      label: "Wine",
      items: [
        {code: "WN01", name: "Angel's Estate Sauvignon Blanc", desc: "white wines (bottle)", eur: 14.31, bgn: 28.00, weight: "750 ml"},
        {code: "WN02", name: "Angel's Estate Chardonnay", desc: "white wines (bottle)", eur: 14.31, bgn: 28.00, weight: "750 ml"},
        {code: "WN03", name: "Purcari 1827 Viorica", desc: "white wines (bottle)", eur: 19.43, bgn: 38.00, weight: "750 ml"},
        {code: "WN04", name: "Purcari 1827 Sauvignon Blanc", desc: "white wines (bottle)", eur: 19.43, bgn: 38.00, weight: "750 ml"},
        {code: "WN05", name: "Angel's Estate Rosé", desc: "rosé wines (bottle)", eur: 14.31, bgn: 28.00, weight: "750 ml"},
        {code: "WN06", name: "Purcari 1827 Rosé", desc: "rosé wines (bottle)", eur: 19.43, bgn: 38.00, weight: "750 ml"},
        {code: "WN07", name: "Angel's Estate Merlot", desc: "red wines (bottle)", eur: 14.31, bgn: 28.00, weight: "750 ml"},
        {code: "WN08", name: "Angel's Estate Cabernet Sauvignon", desc: "red wines (bottle)", eur: 14.31, bgn: 28.00, weight: "750 ml"},
        {code: "WN09", name: "Stallion Selection Syrah", desc: "red wines (bottle)", eur: 19.43, bgn: 38.00, weight: "750 ml"},
        {code: "WN10", name: "Stallion Selection Cabernet Franc", desc: "red wines (bottle)", eur: 19.43, bgn: 38.00, weight: "750 ml"},
        {code: "WN11", name: "Stallion Classic", desc: "Cabernet Sauvignon / Cabernet Franc / Syrah / Merlot", eur: 26.59, bgn: 52.00, weight: "750 ml"},
        {code: "WN12", name: "Purcari 1827 Cabernet Sauvignon", desc: "red wines (bottle)", eur: 19.43, bgn: 38.00, weight: "750 ml"},
        {code: "WN13", name: "Angel's Valley Sauvignon Blanc", desc: "bulk wine (glass)", eur: 3.02, bgn: 5.90, weight: "200 ml"},
        {code: "WN14", name: "Angel's Valley Sauvignon Blanc", desc: "bulk wine (carafe)", eur: 7.16, bgn: 14.00, weight: "500 ml"},
        {code: "WN15", name: "Angel's Valley Syrah", desc: "bulk wine (glass)", eur: 3.02, bgn: 5.90, weight: "200 ml"},
        {code: "WN16", name: "Angel's Valley Syrah", desc: "bulk wine (carafe)", eur: 7.16, bgn: 14.00, weight: "500 ml"}
      ]
    } 
  ]
};