window.MENU_ES = {
  currency: "lv",
  categories: [
{
  id: "specialni",
  label: "ESPECIALES",
  items: [
    {code:"S01", name:"Tomate de invierno", desc:"tomate asado, katak (pasta láctea búlgara), aceitunas, nueces, pesto de ajo silvestre", eur:"7.11", bgn:"13.90", weight:"400 г"},
    {code:"S02", name:"Verduras fermentadas", desc:"verduras mixtas tradicionales lactofermentadas", eur:"5.22", bgn:"10.20", weight:"300 г"},
    {code:"S03", name:"Paprika u pavlak", desc:"untable picante de pimientos con crema agria", eur:"5.06", bgn:"9.90", weight:"200 г"},
    {code:"S04", name:"Kyopolou con bruschetta y nueces", desc:"pasta tradicional de berenjena y pimientos asados, servida con bruschetta", eur:"5.06", bgn:"9.90", weight:"250 г"},
    {code:"S05", name:"Bruschetta con tocino ibérico curado y tomates cherry", desc:"pan tostado con tocino ibérico curado y tomates cherry", eur:"6.08", bgn:"11.90", weight:"250 г"},
    {code:"S06", name:"Bumbar", desc:"embutido tradicional a la parrilla de casquería con arroz y especias", eur:"6.60", bgn:"12.90", weight:"250 г"},
    {code:"S07", name:"Rollitos de col rellenos", desc:"rollitos de col de chucrut rellenos de carne picada y arroz", eur:"6.44", bgn:"12.60", weight:"250 г"},
    {code:"S08", name:"Sudzhuk casero con verduras fermentadas", desc:"sudzhuk casero fresco a la parrilla, servido con verduras fermentadas", eur:"9.00", bgn:"17.60", weight:"450 г"},
    {code:"S09", name:"Albóndigas retro mixtas", desc:"tres albóndigas de cerdo, cordero y ternera, lyutenitsa casera (pasta de pimientos y tomate), verduras fermentadas y patatas fritas", eur:"8.13", bgn:"15.90", weight:"450 г"},
    {code:"S10", name:"Panceta de cerdo a la parrilla", desc:"panceta de cerdo a la parrilla, lyutenitsa casera (pasta de pimientos y tomate), verduras fermentadas y guindilla picante", eur:"8.08", bgn:"15.80", weight:"400 г"},
    {code:"S11", name:"Kachamak con huevo, sudzhuk y queso", desc:"gachas tradicionales de harina de maíz (tipo polenta) con huevo, sudzhuk y queso blanco", eur:"7.11", bgn:"13.90", weight:"450 г"},
    {code:"S12", name:"Orejas de cerdo a la parrilla", desc:"orejas de cerdo a la parrilla", eur:"7.06", bgn:"13.80", weight:"250 г"},
    {code:"S13", name:"Jarrete de cerdo con manita", desc:"jarrete de cerdo cocido a fuego lento y manita de cerdo, cebolla caramelizada y judías", eur:"8.64", bgn:"16.90", weight:"350 г"},
    {code:"S14", name:"Panceta de cerdo asada lentamente", desc:"panceta de cerdo asada al horno con patatas rústicas y ensalada", eur:"11.20", bgn:"21.90", weight:"450 г"},
    {code:"S15", name:"Jarrete de cerdo asado", desc:"jarrete de cerdo asado con patatas rústicas y ensalada", eur:"12.73", bgn:"24.90", weight:"890 г"},
    {code:"S16", name:"Jarrete de cerdo con chucrut y arroz", desc:"jarrete de cerdo cocinado con chucrut y arroz", eur:"9.15", bgn:"17.90", weight:"450 г"}
  ]
},

{
  id: "ribni",
  label: "PESCADOS",
  items: [
    {code:"F01", name:"Tarama", desc:"crema clásica de huevas de pescado con cebolla roja y pan plano", eur:"5.57", bgn:"10.90", weight:"180/100 g"},
    {code:"F02", name:"Ensalada de atún", desc:"lechuga, tomates, atún en conserva, maíz dulce y limón", eur:"7.10", bgn:"13.90", weight:"400 g"},
    {code:"F03", name:"Filete de gavro ligeramente curado", desc:"filete de gavro curado, aceite de oliva, cebolla, limón y pan tostado", eur:"5.27", bgn:"10.30", weight:"130 g"},
    {code:"F04", name:"Set de meze para compartir", desc:"tzatziki, tyrokafteri, tarama, aceitunas, gavro curado y pan plano", eur:"7.87", bgn:"15.40", weight:"350 g"},
    {code:"F05", name:"Gambas al estilo griego", desc:"gambas salteadas con ajo y ouzo", eur:"8.64", bgn:"16.90", weight:"200 g"},
    {code:"F06", name:"Gambas saganaki", desc:"gambas cocinadas con tomates, hierbas y queso", eur:"9.00", bgn:"17.60", weight:"350 g"},
    {code:"F07", name:"Mejillones salteados", desc:"mejillones salteados con mantequilla, cebolla tierna, ajo, eneldo y hierbas", eur:"7.06", bgn:"13.80", weight:"400 g"},
    {code:"F08", name:"Mejillones en concha", desc:"mejillones al vapor", eur:"7.06", bgn:"13.80", weight:"500 g"},
    {code:"F09", name:"Mejillones saganaki", desc:"mejillones cocinados con tomates, hierbas y queso", eur:"8.59", bgn:"16.80", weight:"350 g"},
    {code:"F10", name:"Calamar a la parrilla", desc:"calamar a la parrilla", eur:"11.04", bgn:"21.60", weight:"350 g"},
    {code:"F11", name:"Calamares fritos", desc:"calamares fritos", eur:"11.04", bgn:"21.60", weight:"350 g"},
    {code:"F12", name:"Safrid frito", desc:"safrid frito", eur:"6.95", bgn:"13.60", weight:"250 g"},
    {code:"F13", name:"Safrid a la parrilla", desc:"safrid a la parrilla", eur:"6.95", bgn:"13.60", weight:"250 g"},
    {code:"F14", name:"Gavro frito", desc:"gavro frito", eur:"6.95", bgn:"13.60", weight:"250 g"},
    {code:"F15", name:"Sardinas fritas", desc:"sardinas fritas", eur:"6.95", bgn:"13.60", weight:"250 g"},
    {code:"F16", name:"Trucha a la parrilla", desc:"trucha entera a la parrilla", eur:"10.17", bgn:"19.90", weight:"400 g"},
    {code:"F17", name:"Lubina a la parrilla", desc:"lubina entera a la parrilla", eur:"11.71", bgn:"22.90", weight:"500 g"},
    {code:"F18", name:"Dorada a la parrilla", desc:"dorada entera a la parrilla", eur:"11.71", bgn:"22.90", weight:"500 g"},
    {code:"F19", name:"Pulpo con tomates cherry y aceitunas", desc:"pulpo salteado con tomates cherry, aceitunas y verduras", eur:"17.90", bgn:"35.00", weight:"150/150 g"},
    {code:"F20", name:"Linguini con mariscos", desc:"pasta linguini con gambas, mejillones y calamares en salsa de tomate", eur:"8.95", bgn:"17.50", weight:"400 g"},
    {code:"F21", name:"Ancas de rana a la provenzal", desc:"ancas de rana salteadas con ajo, mantequilla y perejil", eur:"8.85", bgn:"17.30", weight:"6 pcs"},
    {code:"F22", name:"Ancas de rana empanadas", desc:"ancas de rana empanadas y fritas", eur:"8.54", bgn:"16.70", weight:"5 pcs"}
  ]
},
{
  id: "salads",
  label: "ENSALADAS",
  items: [
    {code:"SA01", name:"Shopska", desc:"tomates, pepinos y queso blanco", eur:"5.37", bgn:"10.50", weight:"400 g"},
    {code:"SA02", name:"Ensalada de tomates", desc:"tomates frescos", eur:"5.01", bgn:"9.80", weight:"330 g"},
    {code:"SA03", name:"Ensalada de tomates con queso blanco", desc:"tomates y queso blanco búlgaro", eur:"5.32", bgn:"10.40", weight:"380 g"},
    {code:"SA04", name:"Ensalada de tomates con katak", desc:"tomates con katak (pasta láctea búlgara)", eur:"5.42", bgn:"10.60", weight:"400 g"},
    {code:"SA05", name:"Tomates y pimientos asados con katak", desc:"tomates, pimientos asados y katak", eur:"5.98", bgn:"11.70", weight:"450 g"},
    {code:"SA06", name:"Tomates, pimientos asados y queso blanco", desc:"tomates, pimientos asados y queso blanco", eur:"5.98", bgn:"11.70", weight:"400 g"},
    {code:"SA07", name:"Ensalada de pepino", desc:"pepinos frescos", eur:"5.01", bgn:"9.80", weight:"330 g"},
    {code:"SA08", name:"Pimientos asados con cebolla", desc:"pimientos asados y cebolla", eur:"5.06", bgn:"9.90", weight:"280 g"},
    {code:"SA09", name:"Pimientos asados con ajo", desc:"pimientos asados y ajo", eur:"5.06", bgn:"9.90", weight:"260 g"},
    {code:"SA10", name:"Ensalada de col y zanahoria", desc:"col blanca y zanahorias", eur:"4.55", bgn:"8.90", weight:"300 g"},
    {code:"SA11", name:"Katak con pimientos asados", desc:"katak (pasta láctea búlgara) con pimientos asados", eur:"5.42", bgn:"10.60", weight:"200 g"},
    {code:"SA12", name:"Ensalada campesina", desc:"tomates, pepinos, pimiento asado, cebolla y queso blanco", eur:"5.57", bgn:"10.90", weight:"450 g"},
    {code:"SA13", name:"Ensalada del pastor", desc:"tomates, pepinos, pimiento, cebolla, jamón, maíz dulce, queso amarillo y queso blanco", eur:"6.75", bgn:"13.20", weight:"500 g"},
    {code:"SA14", name:"Ensalada griega", desc:"tomates, pepinos, pimientos asados, cebolla, queso blanco, aceitunas, orégano y aceite de oliva", eur:"5.88", bgn:"11.50", weight:"430 g"},
    {code:"SA15", name:"Ensalada César", desc:"lechuga iceberg, rúcula, tomates cherry, pechuga de pollo, parmesano, picatostes y salsa César", eur:"7.31", bgn:"14.30", weight:"350 g"},
    {code:"SA16", name:"Ensalada balcánica", desc:"tomates, pimiento asado, calabacín y berenjena a la parrilla, queso de oveja, pesto y pasta de ajo", eur:"7.06", bgn:"13.80", weight:"350 g"},
    {code:"SA17", name:"Ensalada caprese", desc:"tomates, mozzarella, pesto y aceite de oliva", eur:"7.10", bgn:"13.90", weight:"350 g"},
    {code:"SA18", name:"Ensalada de atún", desc:"lechuga, tomates, atún en conserva, maíz dulce y limón", eur:"7.10", bgn:"13.90", weight:"350 g"},
    {code:"SA19", name:"Ensalada verde con huevo", desc:"lechuga, pepinos, cebolla tierna y huevo", eur:"5.62", bgn:"11.00", weight:"350 g"},
    {code:"SA20", name:"Ensalada láctea", desc:"yogur, pepinos, ajo y nueces", eur:"5.06", bgn:"9.90", weight:"200 g"},
    {code:"SA21", name:"Ensalada de huevo y patata", desc:"huevo y patatas cocidas con mayonesa y mostaza", eur:"5.06", bgn:"9.90", weight:"200 g"},
    {code:"SA22", name:"Tomate de invierno", desc:"tomate asado, katak, aceitunas, nueces y pesto de ajo silvestre", eur:"6.60", bgn:"12.90", weight:"350 g"},
    {code:"SA23", name:"Ensalada de espinaca baby y queso azul", desc:"mezcla de hojas verdes, rúcula, espinaca baby, tomates secos, queso azul, nueces y aliño", eur:"7.10", bgn:"13.90", weight:"300 g"},
    {code:"SA24", name:"Ensalada de alubias y setas", desc:"alubias, setas, aceitunas, pimiento asado y pepinillos", eur:"5.57", bgn:"10.90", weight:"350 g"},
    {code:"SA25", name:"Ensalada King Edward", desc:"queso blanco, queso amarillo, huevo, mayonesa y pepinillos", eur:"5.57", bgn:"10.90", weight:"300 g"},
    {code:"SA26", name:"Ensalada de tomates con queso azul", desc:"tomates, queso azul, queso blanco, aceite de oliva y orégano", eur:"6.39", bgn:"12.50", weight:"320 g"},
    {code:"SA27", name:"Ensalada Filibe", desc:"berenjena, calabacín y pimientos marinados, aceitunas y queso de oveja", eur:"7.98", bgn:"15.60", weight:"400 g"},
    {code:"SA28", name:"Ensalada Zhekova", desc:"tomates, pimiento asado, cebolla y queso blanco horneado", eur:"5.98", bgn:"11.70", weight:"400 g"},
    {code:"SA29", name:"Meze de ouzo", desc:"tomate, queso de oveja, aceitunas, kyopolou, solomillo de cerdo, bruschetta y guindilla picante", eur:"7.72", bgn:"15.10", weight:"450 g"},
    {code:"SA30", name:"Verduras fermentadas", desc:"verduras fermentadas tradicionales", eur:"5.22", bgn:"10.20", weight:"300 g"},
    {code:"SA31", name:"Aceitunas Kalamata con cebolla", desc:"aceitunas Kalamata y cebolla", eur:"5.06", bgn:"9.90", weight:"220 g"},
    {code:"SA32", name:"Patatas cocidas con cebolla", desc:"patatas cocidas y cebolla", eur:"4.60", bgn:"9.00", weight:"400 g"}
  ]
},
{
  id: "razqdki",
  label: "ENTRANTES",
  items: [
    {code:"RZ01", name:"Tzatziki", desc:"", eur:"5.06", bgn:"9.90", weight:"200 г"},
    {code:"RZ02", name:"Tyrokafteri", desc:"untable picante de queso con guindillas", eur:"5.06", bgn:"9.90", weight:"150 г"},
    {code:"RZ03", name:"Katak", desc:"katak (pasta láctea búlgara)", eur:"5.06", bgn:"9.90", weight:"200 г"},
    {code:"RZ04", name:"Hummus con bruschetta", desc:"", eur:"5.06", bgn:"9.90", weight:"250 г"},
    {code:"RZ05", name:"Kyopolou con bruschetta y nueces", desc:"pasta tradicional de berenjena y pimientos asados", eur:"5.06", bgn:"9.90", weight:"250 г"},
    {code:"RZ06", name:"Tarama con pita griega", desc:"", eur:"5.57", bgn:"10.90", weight:"180/100 г"},
    {code:"RZ07", name:"Meze de ouzo", desc:"tomate, queso blanco, aceitunas, kyopolou, solomillo de cerdo y bruschetta", eur:"7.72", bgn:"15.10", weight:"450 г"},
    {code:"RZ08", name:"Filete de gavro ligeramente curado", desc:"filete de gavro curado con cebolla, aceite de oliva y limón", eur:"5.27", bgn:"10.30", weight:"130 г"},
    {code:"RZ09", name:"Paprika u pavlak", desc:"untable picante de crema con guindillas", eur:"5.06", bgn:"9.90", weight:"200 г"},
    {code:"RZ10", name:"Set de meze para compartir", desc:"tzatziki, tyrokafteri, tarama, aceitunas, gavro curado y pita griega", eur:"7.87", bgn:"15.40", weight:"350 г"}
  ]
},
{
  id: "predqstiq_bez_meso",
  label: "ENTRANTES SIN CARNE",
  items: [
    {code:"PB01", name:"Pimientos bŷurek", desc:"pimientos fritos rellenos de queso", eur:"6.08", bgn:"11.90", weight:"2 pcs"},
    {code:"PB02", name:"Pimientos en salsa de tomate", desc:"pimientos en salsa de tomate", eur:"6.60", bgn:"12.90", weight:"400 g"},
    {code:"PB03", name:"Champiñones rellenos", desc:"champiñones, queso blanco, queso amarillo y ajo", eur:"6.60", bgn:"12.90", weight:"250 g"},
    {code:"PB04", name:"Calabacín frito con salsa de yogur al ajo", desc:"calabacín frito con salsa de yogur al ajo", eur:"6.44", bgn:"12.60", weight:"300 g"},
    {code:"PB05", name:"Berenjena en salsa de tomate", desc:"berenjena en salsa de tomate", eur:"6.60", bgn:"12.90", weight:"400 g"},
    {code:"PB06", name:"Verduras en salsa cremosa de queso", desc:"brócoli, coliflor, champiñones, cebolla, maíz dulce, guisantes, zanahorias, nata y queso fundido", eur:"6.60", bgn:"12.90", weight:"500 g"},
    {code:"PB07", name:"Verduras a la parrilla", desc:"calabacín, berenjena, patatas, champiñones, cebolla y pimientos", eur:"6.60", bgn:"12.90", weight:"500 g"},
    {code:"PB08", name:"Brócoli a la mantequilla", desc:"brócoli con mantequilla", eur:"6.08", bgn:"11.90", weight:"300 g"},
    {code:"PB09", name:"Brócoli con queso fundido y nata", desc:"brócoli, nata, queso fundido y queso amarillo", eur:"6.60", bgn:"12.90", weight:"400 g"},
    {code:"PB10", name:"Brócoli empanado", desc:"brócoli empanado", eur:"6.49", bgn:"12.70", weight:"350 g"},
    {code:"PB11", name:"Croquetas de espinaca", desc:"croquetas de espinaca fritas", eur:"6.60", bgn:"12.90", weight:"500 g"},
    {code:"PB12", name:"Croquetas de calabacín", desc:"croquetas de calabacín fritas", eur:"6.60", bgn:"12.90", weight:"500 g"},
    {code:"PB13", name:"Queso al horno estilo Shopska", desc:"queso blanco, tomate, pimiento asado y huevo", eur:"5.57", bgn:"10.90", weight:"250 g"},
    {code:"PB14", name:"Queso a la plancha con miel y nueces", desc:"queso blanco al horno con miel y nueces", eur:"5.57", bgn:"10.90", weight:"230 g"},
    {code:"PB15", name:"Bocados de queso ahumado en cornflakes", desc:"servido con mermelada de arándanos", eur:"6.08", bgn:"11.90", weight:"250 g"},
    {code:"PB16", name:"Queso blanco rebozado en cerveza", desc:"servido con mermelada de arándanos", eur:"6.80", bgn:"13.30", weight:"250 g"},
    {code:"PB17", name:"Queso amarillo rebozado en cerveza", desc:"", eur:"6.80", bgn:"13.30", weight:"250 g"},
    {code:"PB18", name:"Queso amarillo empanado", desc:"queso amarillo empanado", eur:"6.49", bgn:"12.70", weight:"200 g"},
    {code:"PB19", name:"Queso amarillo a la plancha", desc:"queso amarillo a la plancha", eur:"6.39", bgn:"12.50", weight:"200 g"},
    {code:"PB20", name:"Patatas al horno con mezcla de quesos", desc:"patatas, nata, queso fundido, queso azul, queso blanco y queso amarillo", eur:"6.60", bgn:"12.90", weight:"500 g"},
    {code:"PB21", name:"Patatas fritas frescas", desc:"patatas fritas de corte fresco", eur:"3.83", bgn:"7.50", weight:"500 g"},
    {code:"PB22", name:"Patatas fritas frescas con queso", desc:"patatas fritas de corte fresco con queso", eur:"4.09", bgn:"8.00", weight:"550 g"},
    {code:"PB23", name:"Patatas fritas", desc:"patatas fritas", eur:"3.83", bgn:"7.50", weight:"350 g"},
    {code:"PB24", name:"Patatas fritas con queso", desc:"patatas fritas con queso", eur:"4.09", bgn:"8.00", weight:"400 g"},
    {code:"PB25", name:"Μish-mash", desc:"huevos, queso blanco, pimientos, cebolla y tomate", eur:"5.73", bgn:"11.20", weight:"350 g"}
  ]
},
{
  id: "predqstiq_s_meso",
  label: "ENTRANTES CON CARNE",
  items: [
    {code:"PM01", name:"Sarmas de col", desc:"rollitos de col rellenos", eur:"6.14", bgn:"12.60", weight:"250 g"},
    {code:"PM02", name:"Sarmas de hoja de parra", desc:"hojas de parra rellenas", eur:"6.14", bgn:"12.60", weight:"250 g"},
    {code:"PM03", name:"Lengua de ternera a la mantequilla", desc:"", eur:"8.13", bgn:"15.90", weight:"180 g"},
    {code:"PM04", name:"Lengua de ternera empanada", desc:"", eur:"8.59", bgn:"16.80", weight:"220 g"},
    {code:"PM05", name:"Lengua con quesos en cazuelita", desc:"lengua de ternera, queso fundido, queso azul, queso blanco y nata", eur:"8.39", bgn:"16.40", weight:"250 g"},
    {code:"PM06", name:"Callos a la mantequilla", desc:"", eur:"6.60", bgn:"12.90", weight:"200 g"},
    {code:"PM07", name:"Callos con champiñones y queso amarillo", desc:"", eur:"7.52", bgn:"14.70", weight:"300 g"},
    {code:"PM08", name:"Cabeza de cordero cocinada lentamente", desc:"", eur:"8.23", bgn:"16.10", weight:"1 pc"},
    {code:"PM09", name:"Despojos de cordero a la mantequilla", desc:"", eur:"6.80", bgn:"13.30", weight:"180 g"},
    {code:"PM10", name:"Despojos mixtos al horno en cazuela de barro", desc:"hígado de cerdo, lengua de ternera, callos de ternera y queso amarillo", eur:"6.22", bgn:"16.00", weight:"350 g"},
    {code:"PM11", name:"Hígados de pollo a la mantequilla", desc:"", eur:"6.60", bgn:"12.90", weight:"300 g"},
    {code:"PM12", name:"Hígados de pollo al estilo campesino", desc:"hígados de pollo con cebolla, pimientos, champiñones y tomates", eur:"7.52", bgn:"14.70", weight:"450 g"},
    {code:"PM13", name:"Hígado de cerdo frito", desc:"", eur:"6.60", bgn:"12.90", weight:"250 g"},
    {code:"PM14", name:"Mollejas de pollo empanadas", desc:"", eur:"6.60", bgn:"12.90", weight:"300 g"},
    {code:"PM15", name:"Corazones de pollo a la mantequilla", desc:"", eur:"6.60", bgn:"12.90", weight:"200 g"},
    {code:"PM16", name:"Corazones de pollo con cebolla, champiñones y queso fundido", desc:"", eur:"7.11", bgn:"13.90", weight:"380 g"},
    {code:"PM17", name:"Corazones de pollo con champiñones y queso amarillo", desc:"", eur:"7.11", bgn:"13.90", weight:"320 g"},
    {code:"PM18", name:"Despojos de pollo mixtos", desc:"hígados, corazones, mollejas y queso amarillo", eur:"8.13", bgn:"15.90", weight:"400 g"},
    {code:"PM19", name:"Bocados de pollo en cornflakes", desc:"", eur:"6.60", bgn:"12.90", weight:"300 g"},
    {code:"PM20", name:"Bocados de pollo con sésamo", desc:"", eur:"6.60", bgn:"12.90", weight:"300 g"},
    {code:"PM21", name:"Bocados de pollo con miel y salsa de soja", desc:"", eur:"6.60", bgn:"12.90", weight:"250 g"},
    {code:"PM22", name:"Patatas al horno con bacon y queso", desc:"patatas, bacon, nata y queso amarillo", eur:"6.60", bgn:"12.90", weight:"500 g"},
    {code:"PM23", name:"Meze Rockeri de pollo", desc:"pollo salteado con champiñones, ajo y salsa de soja", eur:"6.60", bgn:"12.90", weight:"300 g"},
    {code:"PM24", name:"Meze Rockeri de cerdo", desc:"cerdo salteado con champiñones, ajo y salsa de soja", eur:"7.16", bgn:"14.00", weight:"300 g"},
    {code:"PM25", name:"Alitas de pollo en salsa de soja", desc:"", eur:"6.90", bgn:"13.50", weight:"350 g"},
    {code:"PM26", name:"Mollejas de pollo a la mantequilla", desc:"", eur:"6.44", bgn:"12.60", weight:"230 g"},
    {code:"PM27", name:"Queso al horno estilo tracio con lukanka", desc:"queso blanco, tomate, pimiento asado, huevo y lukanka", eur:"6.39", bgn:"12.50", weight:"330 g"},
    {code:"PM28", name:"Bumbar", desc:"embutido tradicional a la parrilla de casquería con arroz y especias", eur:"6.60", bgn:"12.90", weight:"250 g"}
  ]
},
{
  id: "pasta",
  label: "PASTA",
  items: [
    {code:"PR01", name:"Risotto de setas del bosque", desc:"risotto con boletus y setas variadas, cebolla y parmesano", eur:"8.13", bgn:"15.90", weight:"400 g"},
    {code:"PR02", name:"Risotto con pollo, espinaca y queso azul", desc:"risotto con pechuga de pollo, espinaca y queso azul", eur:"8.13", bgn:"15.90", weight:"400 g"},
    {code:"PR03", name:"Risotto de verduras", desc:"risotto con pimientos, zanahorias, apio, brócoli y calabacín", eur:"8.13", bgn:"15.90", weight:"400 g"},
    {code:"PR04", name:"Espaguetis a la boloñesa", desc:"espaguetis con salsa clásica de carne", eur:"8.28", bgn:"16.20", weight:"400 g"},
    {code:"PR05", name:"Espaguetis carbonara", desc:"", eur:"8.28", bgn:"16.20", weight:"400 g"}
  ]
},
{
  id: "osnowni",
  label: "PRINCIPALES",
  items: [
    {code:"M01", name:"Filete de pollo Tracia", desc:"filete de pollo, ajo, vino blanco, patatas salteadas", weight:"250 г", eur:"7.57", bgn:"14.80"},
    {code:"M02", name:"Filete de pollo del maestro", desc:"filete de pollo, tomates, queso amarillo, albahaca", weight:"350 г", eur:"7.67", bgn:"15.00"},
    {code:"M03", name:"Kavarma de pollo", desc:"filete de pollo, champiñones, cebolla, pimiento, tomates", weight:"400 г", eur:"8.13", bgn:"15.90"},
    {code:"M04", name:"Filete de pollo con champiñones", desc:"", weight:"350 г", eur:"7.62", bgn:"14.90"},
    {code:"M05", name:"Chuleta de pollo con queso azul", desc:"chuleta de pollo, queso azul, nata, patatas salteadas", weight:"500 г", eur:"8.13", bgn:"15.90"},
    {code:"M06", name:"Inspiración de los Ródopes", desc:"chuleta de pollo, cebolla, champiñones, ajo, tomates, especias", weight:"350 г", eur:"7.87", bgn:"15.40"},
    {code:"M07", name:"Pollo con verduras", desc:"filete de pollo, zanahoria, pepino, pimiento, champiñones, berenjena", weight:"400 г", eur:"7.62", bgn:"14.90"},
    {code:"M08", name:"Pollo con brócoli y nata", desc:"", weight:"380 г", eur:"7.62", bgn:"14.90"},
    {code:"M09", name:"Codillo de cerdo asado", desc:"", weight:"800 г", eur:"12.73", bgn:"24.90"},
    {code:"M10", name:"Meze Kateno", desc:"cerdo, pollo, cebolla, champiñones, pepinillo encurtido", weight:"400 г", eur:"8.03", bgn:"15.70"},
    {code:"M11", name:"Carré de cerdo a la sartén", desc:"", weight:"200 г", eur:"7.11", bgn:"13.90"},
    {code:"M12", name:"Kavarma de cerdo", desc:"carne de cerdo, cebolla, champiñones, pimiento, tomates", weight:"400 г", eur:"8.13", bgn:"15.90"},
    {code:"M13", name:"Cordero asado", desc:"cordero, patatas asadas y ensalada verde", weight:"450 г", eur:"16.87", bgn:"33.00"},
    {code:"M14", name:"Solomillo de cerdo con salsa de miel y ajo", desc:"", weight:"300 г", eur:"7.93", bgn:"15.50"},
    {code:"M15", name:"Ternera joven", desc:"ternera, patatas rústicas y ensalada verde", weight:"400 г", eur:"12.73", bgn:"24.90"},
    {code:"M16", name:"Solomillo de cerdo con champiñones", desc:"", weight:"350 г", eur:"7.93", bgn:"15.50"},
    {code:"M17", name:"Kebap drusan", desc:"cuello de cerdo, cebolla, especias, guindilla picante", weight:"350 г", eur:"7.62", bgn:"14.90"},
    {code:"M18", name:"Chuleta de leñador", desc:"cuello de cerdo, calabacín, berenjena, champiñones, pimiento", weight:"450 г", eur:"8.13", bgn:"15.90"},
    {code:"M19", name:"Panceta de cerdo al horno", desc:"panceta de cerdo asada, patatas rústicas, ensalada", weight:"450 г", eur:"11.20", bgn:"21.90"}
  ]
},
{
  id: "skara",
  label: "PARRILLA",
  items: [
    {code:"G01", name:"Albóndigas retro mixtas", desc:"tres albóndigas a la parrilla de cerdo, cordero y ternera, con patatas fritas, ensalada de temporada y lutenitsa casera", weight:"300/250 г", eur:"8.13", bgn:"15.90"},
    {code:"G02", name:"Panceta de cerdo a la parrilla", desc:"panceta de cerdo a la parrilla con lutenitsa casera, ensalada de temporada y guindilla picante", weight:"250/250 г", eur:"8.08", bgn:"15.80"},
    {code:"G03", name:"Filete / chuleta de pollo a la parrilla", desc:"", weight:"220/250 г", eur:"7.06", bgn:"13.80"},
    {code:"G04", name:"Albóndigas de ternera Black Angus en brocheta", desc:"dos brochetas, ensalada fresca, patatas rústicas y salsa chimichurri", weight:"240/200 г", eur:"8.64", bgn:"16.90"},
    {code:"G05", name:"Alitas de pollo a la parrilla", desc:"", weight:"350 г", eur:"6.90", bgn:"13.50"},
    {code:"G06", name:"Costillas de cerdo a la parrilla", desc:"", weight:"500 г", eur:"9.63", bgn:"18.90"},
    {code:"G07", name:"Cuello de cerdo a la parrilla", desc:"", weight:"250 г", eur:"7.26", bgn:"14.20"},
    {code:"G08", name:"Solomillo de cerdo a la parrilla", desc:"", weight:"230 г", eur:"8.08", bgn:"15.80"},
    {code:"G09", name:"Carré de cerdo a la parrilla", desc:"", weight:"200 г", eur:"7.11", bgn:"13.90"},
    {code:"G10", name:"Corazones de pato a la parrilla", desc:"", weight:"200 г", eur:"7.62", bgn:"14.90"}
  ]
},
{
  id: "kum_qstiqta",
  label: "GUARNICIONES",
  items: [
    {code:"KJ01", name:"Guarnición de tomate y pepino", desc:"", weight:"160 г", eur:"2.20", bgn:"4.30"},
    {code:"KJ02", name:"Guarnición de patatas hervidas con cebolla", desc:"", weight:"250 г", eur:"2.05", bgn:"4.00"},
    {code:"KJ03", name:"Guarnición de patatas fritas", desc:"", weight:"200 г", eur:"2.05", bgn:"4.00"},
    {code:"KJ04", name:"Guarnición de patatas fritas con queso blanco", desc:"", weight:"230 г", eur:"2.20", bgn:"4.30"},
    {code:"KJ05", name:"Guarnición de col y zanahoria", desc:"", weight:"150 г", eur:"2.05", bgn:"4.00"},
    {code:"KJ06", name:"Rebanada de pan", desc:"", weight:"1 бр", eur:"0.36", bgn:"0.70"},
    {code:"KJ07", name:"Rebanada de pan con ajo", desc:"", weight:"1 бр", eur:"0.77", bgn:"1.50"},
    {code:"KJ08", name:"Pan casero", desc:"", weight:"1 бр", eur:"3.53", bgn:"6.90"},
    {code:"KJ09", name:"Pan plano con ajo", desc:"", weight:"1 бр", eur:"2.15", bgn:"4.20"},
    {code:"KJ10", name:"Pan plano con queso blanco", desc:"", weight:"1 бр", eur:"2.45", bgn:"4.80"},
    {code:"KJ11", name:"Pan plano con queso amarillo", desc:"", weight:"1 бр", eur:"2.66", bgn:"5.20"},
    {code:"KJ12", name:"Pan plano combinado", desc:"", weight:"1 бр", eur:"2.86", bgn:"5.60"},
    {code:"KJ13", name:"Guindilla picante", desc:"", weight:"1 бр", eur:"0.61", bgn:"1.20"},
    {code:"KJ14", name:"Salsa", desc:"", weight:"50 мл", eur:"1.02", bgn:"2.00"},
    {code:"KJ15", name:"Lyutenitsa", desc:"", weight:"60 г", eur:"1.53", bgn:"3.00"},
    {code:"KJ16", name:"Kétchup / mostaza / yogur", desc:"", weight:"50 мл", eur:"1.02", bgn:"2.00"},
    {code:"KJ17", name:"Huevo", desc:"", weight:"1 бр", eur:"1.02", bgn:"2.00"},
    {code:"KJ18", name:"Limón", desc:"", weight:"1/2 бр", eur:"1.02", bgn:"2.00"},
    {code:"KJ19", name:"Sudzhuk casero / filete de cerdo", desc:"", weight:"50 г", eur:"2.81", bgn:"5.50"},
    {code:"KJ20", name:"Queso blanco de vaca", desc:"", weight:"50 г", eur:"1.48", bgn:"2.90"},
    {code:"KJ21", name:"Queso de oveja / cabra", desc:"", weight:"50 г", eur:"2.30", bgn:"4.50"},
    {code:"KJ22", name:"Queso azul", desc:"", weight:"50 г", eur:"2.56", bgn:"5.00"},
    {code:"KJ23", name:"Queso amarillo", desc:"", weight:"50 г", eur:"2.30", bgn:"4.50"}
  ]
},
{
  id: "deserti",
  label: "POSTRES",
  items: [
    {code:"D01", name:"Helado", desc:"", weight:"150 г", eur:"2.91", bgn:"5.70"},
    {code:"D02", name:"Helados caseros – sabores variados", desc:"", weight:"150 г", eur:"3.74", bgn:"6.60"},
    {code:"D03", name:"Crêpe con chocolate / mermelada", desc:"", weight:"1 бр", eur:"3.02", bgn:"5.90"},
    {code:"D04", name:"Crêpe con miel y nueces", desc:"", weight:"1 бр", eur:"3.02", bgn:"5.90"},
    {code:"D05", name:"Tarta de manzana", desc:"", weight:"1 бр", eur:"3.02", bgn:"5.90"},
    {code:"D06", name:"Soufflé de chocolate con helado", desc:"", weight:"1 бр", eur:"3.17", bgn:"6.20"},
    {code:"D07", name:"Postre del día", desc:"", weight:"", eur:"", bgn:""}
  ]
},
{
  id: "bezalkoholni",
  label: "REFRESCOS",
  items: [
    {code:"BN01", name:"Coca-Cola", desc:"", weight:"250 мл", eur:"1.99", bgn:"3.90"},
    {code:"BN02", name:"Fanta", desc:"", weight:"250 мл", eur:"1.99", bgn:"3.90"},
    {code:"BN03", name:"Sprite", desc:"", weight:"250 мл", eur:"1.99", bgn:"3.90"},
    {code:"BN04", name:"Tónica", desc:"", weight:"250 мл", eur:"1.99", bgn:"3.90"},
    {code:"BN05", name:"Schweppes", desc:"", weight:"250 мл", eur:"1.99", bgn:"3.90"},
    {code:"BN06", name:"Té frío", desc:"", weight:"250 мл", eur:"1.99", bgn:"3.90"},
    {code:"BN07", name:"Agua con gas", desc:"", weight:"300 мл", eur:"1.48", bgn:"2.90"},
    {code:"BN08", name:"Agua mineral", desc:"", weight:"330 мл", eur:"1.48", bgn:"2.90"},
    {code:"BN09", name:"Agua mineral", desc:"", weight:"1 л", eur:"2.25", bgn:"4.40"},
    {code:"BN10", name:"Zumo de tomate casero", desc:"", weight:"500 мл", eur:"3.89", bgn:"7.60"},
    {code:"BN11", name:"Ayran (vaso)", desc:"", weight:"250 мл", eur:"1.79", bgn:"3.50"},
    {code:"BN12", name:"Ayran (jarra)", desc:"", weight:"500 мл", eur:"3.07", bgn:"6.00"},
    {code:"BN13", name:"Limonada casera de lavanda con miel", desc:"", weight:"400 мл", eur:"2.76", bgn:"5.40"},
    {code:"BN14", name:"Limonada casera de lavanda con miel", desc:"", weight:"1 л", eur:"5.93", bgn:"11.60"},
    {code:"BN15", name:"Zumo Cappy", desc:"", weight:"250 мл", eur:"2.10", bgn:"4.10"},
    {code:"BN16", name:"Red Bull", desc:"", weight:"250 мл", eur:"3.42", bgn:"6.70"},
    {code:"BN17", name:"Café", desc:"", weight:"60 мл", eur:"1.33", bgn:"2.60"},
    {code:"BN18", name:"Té", desc:"", weight:"250 мл", eur:"1.33", bgn:"2.60"},
    {code:"BN19", name:"Miel / nata / leche", desc:"", weight:"1 бр", eur:"0.41", bgn:"0.80"}
  ]
},
{
  id: "alcohol",
  label: "ALCOHOL",
  items: [
    {code:"AN01", name:"Peshterska clásica", desc:"", weight:"50 мл", eur:"1.74", bgn:"3.40"},
    {code:"AN02", name:"Peshterska añeja", desc:"", weight:"50 мл", eur:"1.89", bgn:"3.70"},
    {code:"AN03", name:"Karnobatska clásica", desc:"", weight:"50 мл", eur:"1.74", bgn:"3.40"},
    {code:"AN04", name:"Pomoriyska clásica", desc:"", weight:"50 мл", eur:"1.89", bgn:"3.70"},
    {code:"AN05", name:"Pomoriyska especial", desc:"", weight:"50 мл", eur:"2.05", bgn:"4.00"},
    {code:"AN06", name:"Slivenska Perla", desc:"", weight:"50 мл", eur:"2.66", bgn:"5.20"},
    {code:"AN07", name:"Sungurlarska especial", desc:"", weight:"50 мл", eur:"2.45", bgn:"4.80"},
    {code:"AN08", name:"Straldzhanska moscatel", desc:"", weight:"50 мл", eur:"2.66", bgn:"5.20"},
    {code:"AN09", name:"Burgaska moscatel", desc:"", weight:"50 мл", eur:"2.05", bgn:"4.00"},
    {code:"AN10", name:"Burgas 63", desc:"", weight:"50 мл", eur:"2.66", bgn:"5.20"},
    {code:"AN11", name:"Burgas 63 Barril", desc:"", weight:"50 мл", eur:"3.32", bgn:"6.50"},
    {code:"AN12", name:"Troyanska de albaricoque", desc:"", weight:"50 мл", eur:"2.05", bgn:"4.00"},
    {code:"AN13", name:"Troyanska de ciruela añeja", desc:"", weight:"50 мл", eur:"2.05", bgn:"4.00"},
    {code:"AN14", name:"Mastika Botsmanska", desc:"", weight:"50 мл", eur:"1.99", bgn:"3.90"},
    {code:"AN15", name:"Ouzo Mavrommati / Matarelli", desc:"", weight:"50 мл", eur:"2.51", bgn:"4.90"},
    {code:"AN16", name:"Ouzo Paralia", desc:"", weight:"50 мл", eur:"1.79", bgn:"3.50"},
    {code:"AN17", name:"Ouzo Plomari / Vantana / 12", desc:"", weight:"50 мл", eur:"2.15", bgn:"4.20"},
    {code:"AN18", name:"Pernod", desc:"", weight:"50 мл", eur:"2.56", bgn:"5.00"},
    {code:"AN19", name:"Ouzo Vantana", desc:"", weight:"200 мл", eur:"10.17", bgn:"19.90"},
    {code:"AN20", name:"Ouzo Plomari", desc:"", weight:"200 мл", eur:"10.17", bgn:"19.90"},
    {code:"AN21", name:"Ouzo Mini / Ouzo 12", desc:"", weight:"200 мл", eur:"10.17", bgn:"19.90"},
    {code:"AN22", name:"Ouzo Matarelli / Mavrommati", desc:"", weight:"200 мл", eur:"12.22", bgn:"23.90"},
    {code:"AN23", name:"Ouzo Barbayanni", desc:"", weight:"200 мл", eur:"12.22", bgn:"23.90"},
    {code:"AN24", name:"Ouzo Paralia", desc:"", weight:"200 мл", eur:"8.33", bgn:"16.30"},
    {code:"AN25", name:"Licor de menta", desc:"", weight:"50 мл", eur:"1.74", bgn:"3.40"},
    {code:"AN26", name:"Baileys", desc:"", weight:"50 мл", eur:"3.22", bgn:"6.30"},
    {code:"AN27", name:"Jägermeister", desc:"", weight:"50 мл", eur:"2.76", bgn:"5.40"},
    {code:"AN28", name:"Savoy", desc:"", weight:"50 мл", eur:"1.74", bgn:"3.40"},
    {code:"AN29", name:"Targovishte", desc:"", weight:"50 мл", eur:"1.84", bgn:"3.60"},
    {code:"AN30", name:"Zhitnaya", desc:"", weight:"50 мл", eur:"1.84", bgn:"3.60"},
    {code:"AN31", name:"Finlandia", desc:"", weight:"50 мл", eur:"2.51", bgn:"4.90"},
    {code:"AN32", name:"Absolut", desc:"", weight:"50 мл", eur:"2.51", bgn:"4.90"},
    {code:"AN33", name:"Stolichnaya / Russian Standard", desc:"", weight:"50 мл", eur:"2.51", bgn:"4.90"},
    {code:"AN34", name:"Smirnoff", desc:"", weight:"50 мл", eur:"2.51", bgn:"4.90"},
    {code:"AN35", name:"Beluga", desc:"", weight:"50 мл", eur:"5.78", bgn:"11.30"},
    {code:"AN36", name:"Savoy", desc:"", weight:"50 мл", eur:"1.74", bgn:"3.40"},
    {code:"AN37", name:"Johnnie Walker", desc:"", weight:"50 мл", eur:"2.97", bgn:"5.80"},
    {code:"AN38", name:"Johnnie Walker Black", desc:"", weight:"50 мл", eur:"5.52", bgn:"10.80"},
    {code:"AN39", name:"Bushmills / Jameson", desc:"", weight:"50 мл", eur:"2.97", bgn:"5.80"},
    {code:"AN40", name:"Four Roses", desc:"", weight:"50 мл", eur:"2.97", bgn:"5.80"},
    {code:"AN41", name:"Jack Daniel's", desc:"", weight:"50 мл", eur:"4.44", bgn:"8.70"},
    {code:"AN42", name:"Ron", desc:"", weight:"50 мл", eur:"1.74", bgn:"3.40"},
    {code:"AN43", name:"Pliska", desc:"", weight:"50 мл", eur:"1.84", bgn:"3.60"},
    {code:"AN44", name:"Coñac importado", desc:"", weight:"50 мл", eur:"3.07", bgn:"6.00"},
    {code:"AN45", name:"Martini", desc:"", weight:"100 мл", eur:"3.07", bgn:"6.00"},
    {code:"AN46", name:"Beefeater", desc:"", weight:"50 мл", eur:"2.45", bgn:"4.80"}
  ]
},
{
  id: "beer",
  label: "CERVEZA",
  items: [
    {code:"BV01", name:"Kamenitza de barril", desc:"", eur:"2.20", bgn:"4.30", weight:"330 ml"},
    {code:"BV02", name:"Kamenitza de barril", desc:"", eur:"2.66", bgn:"5.20", weight:"500 ml"},
    {code:"BV03", name:"Madri", desc:"", eur:"2.81", bgn:"5.50", weight:"500 ml"},
    {code:"BV04", name:"Franziskaner", desc:"", eur:"5.22", bgn:"10.20", weight:"500 ml"},
    {code:"BV05", name:"Kamenitza", desc:"", eur:"2.66", bgn:"5.20", weight:"500 ml"},
    {code:"BV06", name:"Burgasko", desc:"", eur:"2.66", bgn:"5.20", weight:"500 ml"},
    {code:"BV07", name:"Stella Artois 0.0", desc:"", eur:"3.07", bgn:"6.00", weight:"330 ml"},
    {code:"BV08", name:"Stella Artois", desc:"", eur:"3.22", bgn:"6.30", weight:"500 ml"},
    {code:"BV09", name:"Staropramen", desc:"", eur:"3.02", bgn:"5.90", weight:"500 ml"},
    {code:"BV10", name:"Leffe Blonde / Brune", desc:"", eur:"4.04", bgn:"7.90", weight:"330 ml"},
    {code:"BV11", name:"Corona Extra", desc:"", eur:"3.48", bgn:"6.80", weight:"330 ml"},
    {code:"BV12", name:"Beck's", desc:"", eur:"2.86", bgn:"5.60", weight:"500 ml"}
  ]
},
{
  id: "wine",
  label: "VINO",
  items: [
    {code:"WN01", name:"Angel's Estate Sauvignon Blanc", desc:"vinos blancos (botella)", eur:"14.31", bgn:"28.00", weight:"750 ml"},
    {code:"WN02", name:"Angel's Estate Chardonnay", desc:"vinos blancos (botella)", eur:"14.31", bgn:"28.00", weight:"750 ml"},
    {code:"WN03", name:"Purcari 1827 Viorica", desc:"vinos blancos (botella)", eur:"19.43", bgn:"38.00", weight:"750 ml"},
    {code:"WN04", name:"Purcari 1827 Sauvignon Blanc", desc:"vinos blancos (botella)", eur:"19.43", bgn:"38.00", weight:"750 ml"},
    {code:"WN05", name:"Angel's Estate Rosé", desc:"vinos rosados (botella)", eur:"14.31", bgn:"28.00", weight:"750 ml"},
    {code:"WN06", name:"Purcari 1827 Rosé", desc:"vinos rosados (botella)", eur:"19.43", bgn:"38.00", weight:"750 ml"},
    {code:"WN07", name:"Angel's Estate Merlot", desc:"vinos tintos (botella)", eur:"14.31", bgn:"28.00", weight:"750 ml"},
    {code:"WN08", name:"Angel's Estate Cabernet Sauvignon", desc:"vinos tintos (botella)", eur:"14.31", bgn:"28.00", weight:"750 ml"},
    {code:"WN09", name:"Stallion Selection Syrah", desc:"vinos tintos (botella)", eur:"19.43", bgn:"38.00", weight:"750 ml"},
    {code:"WN10", name:"Stallion Selection Cabernet Franc", desc:"vinos tintos (botella)", eur:"19.43", bgn:"38.00", weight:"750 ml"},
    {code:"WN11", name:"Stallion Classic", desc:"Cabernet Sauvignon / Cabernet Franc / Syrah / Merlot", eur:"26.59", bgn:"52.00", weight:"750 ml"},
    {code:"WN12", name:"Purcari 1827 Cabernet Sauvignon", desc:"vinos tintos (botella)", eur:"19.43", bgn:"38.00", weight:"750 ml"},
    {code:"WN13", name:"Angel's Valley Sauvignon Blanc", desc:"vino a granel (copa)", eur:"3.02", bgn:"5.90", weight:"200 ml"},
    {code:"WN14", name:"Angel's Valley Sauvignon Blanc", desc:"vino a granel (jarra)", eur:"7.16", bgn:"14.00", weight:"500 ml"},
    {code:"WN15", name:"Angel's Valley Syrah", desc:"vino a granel (copa)", eur:"3.02", bgn:"5.90", weight:"200 ml"},
    {code:"WN16", name:"Angel's Valley Syrah", desc:"vino a granel (jarra)", eur:"7.16", bgn:"14.00", weight:"500 ml"}
  ]
}

  ]
};
